version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto17
  pre_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - ./gradlew clean
    - ./gradlew validate
    - echo Build ends on 'date'
  build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - mv./gradlewn compile
    - ./gradlew test
    - echo Build ends on 'date'
  post_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - ./gradlew package
    - mv build/libs/*.jar ROOT.jar
    - echo Build ends on 'date'

artifacts:
  files:
    - ROOT.jar
  name: java-gradle-app